METHOD:
  method: 'FinetuneWithInstanceNorm'
  episodic_training: False
  iter: 100
  finetune_lr: 0.00002
  temp: 10
  finetune_all_layers: False
  eval_metrics: ['Acc', 'XEnt']
  finetune_cosine_head: True
  finetune_weight_norm: True
  hyperparams: ['method', 'arch', 'base_source', 'test_source', 'finetune_all_layers']
  finetune_weight_decay: 0.0001
