TRAINING:
  num_ways: 5
  num_support: 5
  num_query: 20
  val_batch_size: 1
  ignore_dag_ontology: True
  batch_size: 1

MODEL:
  use_fc: False

METHOD:
  method: 'ProtoNet'
  episodic_training: True
  hyperparams: ['method', 'arch', 'base_source', 'test_source']
  eval_metrics: ['Acc']