METHOD:
  method: 'ProtoNet'
  episodic_training: True
  hyperparams: ['method', 'arch', 'base_source', 'test_source']
  eval_metrics: ['Acc']

DATA:
    batch_size: 1
    image_size: 126
    gaussian_noise_std: 0.1533
    jitter_amount: 5
    num_unique_descriptions: 0
    shuffle: True

TRAINING:
  num_updates: 75000

OPTIM:
    gamma: 0.885
    lr: 0.0003
    lr_stepsize: 5000
    weight_decay: 0.0001
    optimizer_name: 'Adam'
    scheduler: 'step'