TRAINING:
  num_ways: 5
  num_support: 5
  num_query: 20
  val_batch_size: 1
  ignore_dag_ontology: True
  batch_size: 1

METHOD:
  method: 'ProtoNet'
  episodic_training: True
  hyperparams: ['method', 'arch', 'base_source', 'test_source']
  eval_metrics: ['Acc']

DATA:
    image_size: 126
    train_transforms: ['random_resized_crop', 'jitter', 'random_flip', 'to_tensor', 'normalize']
    test_transforms: ['resize', 'center_crop', 'to_tensor', 'normalize']
    num_unique_descriptions: 0
    shuffle: True

TRAINING:
  num_updates: 75000

OPTIM:
    gamma: 0.83
    lr: 0.0006
    lr_stepsize: 2500
    nesterov: False
    weight_decay: 0.0002
    optimizer_name: 'Adam'
    scheduler: 'step'